-- *** SCRIPT SỬA LỖI TOÀN DIỆN (FIX ALL ERROR) ***
-- Chạy script này để khắc phục lỗi 400, 406 và lỗi không đăng nhập được Admin.
-- 1. TẠO CÁC BẢNG BỊ THIẾU (Announcements, App Settings, Page Content)
CREATE TABLE IF NOT EXISTS public.announcements (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT CHECK (type IN ('info', 'warning', 'success')) DEFAULT 'info',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settings_data JSONB
);
CREATE TABLE IF NOT EXISTS public.page_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_name TEXT NOT NULL UNIQUE,
    content_data JSONB
);
-- 2. THIẾT LẬP CẤU HÌNH MẶC ĐỊNH
INSERT INTO public.app_settings (id, settings_data)
VALUES (
        1,
        '{
        "siteName": "Beauty Directory",
        "supportEmail": "support@beautydir.com",
        "maintenanceMode": false,
        "bankDetails": {
            "bankName": "MB Bank",
            "accountName": "BEAUTY DIR CO",
            "accountNumber": "0000000000",
            "transferNote": "Payment for order [code]"
        }
    }'::JSONB
    ) ON CONFLICT (id) DO NOTHING;
-- 3. CẤP QUYỀN SUPER ADMIN
-- Thay đổi email bên dưới nếu bạn dùng email khác
INSERT INTO public.admin_users (username, email, role, permissions, is_locked)
VALUES (
        'SuperAdmin',
        'tanloifmc@yahoo.com',
        'Admin',
        '{
        "canManageUsers": true, 
        "canManageOrders": true, 
        "canViewEmailLog": true, 
        "canUseAdminTools": true, 
        "canViewAnalytics": true, 
        "canManagePackages": true, 
        "canViewActivityLog": true, 
        "canManageBusinesses": true, 
        "canManageSiteContent": true, 
        "canManagePlatformBlog": true, 
        "canManageAnnouncements": true, 
        "canManageRegistrations": true, 
        "canManageSupportTickets": true, 
        "canManageSystemSettings": true
    }'::JSONB,
        FALSE
    ) ON CONFLICT (email) DO
UPDATE
SET role = 'Admin',
    permissions = EXCLUDED.permissions,
    is_locked = FALSE;
-- 4. BẬT BẢO MẬT (RLS)
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public announcements view" ON public.announcements;
CREATE POLICY "Public announcements view" ON public.announcements FOR
SELECT USING (true);
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Settings view" ON public.app_settings;
CREATE POLICY "Settings view" ON public.app_settings FOR
SELECT USING (true);
ALTER TABLE public.page_content ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Page content view" ON public.page_content;
CREATE POLICY "Page content view" ON public.page_content FOR
SELECT USING (true);
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin users view" ON public.admin_users;
CREATE POLICY "Admin users view" ON public.admin_users FOR
SELECT USING (true);