-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- *** CẢNH BÁO QUAN TRỌNG / IMPORTANT WARNING ***
-- Script này được thiết kế để "LÀM LẠI TỪ ĐẦU" (Reset from scratch).
-- Nó sẽ XÓA (DROP) các bảng hiện có trước khi tạo lại.
-- Nếu bạn có dữ liệu quan trọng, hãy SAO LƯU trước khi chạy.
--
-- This script performs a FULL RESET. It DROPS existing tables.
-- Backup your data if necessary.

-- DROP existing tables to prevent conflicts (Order matters or use CASCADE)
DROP TABLE IF EXISTS public.support_tickets CASCADE;
DROP TABLE IF EXISTS public.appointments CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.registration_requests CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.business_blog_posts CASCADE;
DROP TABLE IF EXISTS public.blog_posts CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.media_items CASCADE;
DROP TABLE IF EXISTS public.team_members CASCADE;
DROP TABLE IF EXISTS public.deals CASCADE;
DROP TABLE IF EXISTS public.services CASCADE;
DROP TABLE IF EXISTS public.businesses CASCADE;
DROP TABLE IF EXISTS public.admin_users CASCADE;

-- DROP existing types to ensure clean enum definitions
DROP TYPE IF EXISTS public.ticket_status CASCADE;
DROP TYPE IF EXISTS public.deal_status CASCADE;
DROP TYPE IF EXISTS public.appointment_status CASCADE;
DROP TYPE IF EXISTS public.staff_member_role CASCADE;
DROP TYPE IF EXISTS public.review_status CASCADE;
DROP TYPE IF EXISTS public.business_blog_post_status CASCADE;
DROP TYPE IF EXISTS public.media_category CASCADE;
DROP TYPE IF EXISTS public.media_type CASCADE;
DROP TYPE IF EXISTS public.order_status CASCADE;
DROP TYPE IF EXISTS public.admin_user_role CASCADE;
DROP TYPE IF EXISTS public.business_category CASCADE;
DROP TYPE IF EXISTS public.membership_tier CASCADE;

-- Enums (matched with types.ts)
CREATE TYPE public.membership_tier AS ENUM ('VIP', 'Premium', 'Free');
CREATE TYPE public.business_category AS ENUM ('Spa & Massage', 'Hair Salon', 'Nail Salon', 'Beauty Clinic', 'Dental Clinic');
CREATE TYPE public.admin_user_role AS ENUM ('Admin', 'Moderator', 'Editor');
CREATE TYPE public.order_status AS ENUM ('Pending', 'Awaiting Confirmation', 'Completed', 'Rejected');
CREATE TYPE public.media_type AS ENUM ('IMAGE', 'VIDEO');
CREATE TYPE public.media_category AS ENUM ('Uncategorized', 'Interior', 'Exterior', 'Staff', 'Products');
CREATE TYPE public.business_blog_post_status AS ENUM ('Draft', 'Published');
CREATE TYPE public.review_status AS ENUM ('Visible', 'Hidden');
CREATE TYPE public.staff_member_role AS ENUM ('Admin', 'Editor');
CREATE TYPE public.appointment_status AS ENUM ('Pending', 'Confirmed', 'Cancelled', 'Completed');
CREATE TYPE public.deal_status AS ENUM ('Active', 'Expired', 'Scheduled');
CREATE TYPE public.ticket_status AS ENUM ('Open', 'In Progress', 'Closed');

-- Table: businesses
CREATE TABLE public.businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    logo_url TEXT,
    image_url TEXT NOT NULL,
    slogan TEXT,
    categories public.business_category[] NOT NULL,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    district TEXT NOT NULL,
    ward TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    tags TEXT[],
    phone TEXT NOT NULL,
    email TEXT,
    website TEXT,
    youtube_url TEXT,
    rating DOUBLE PRECISION DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    view_count INTEGER DEFAULT 0,
    membership_tier public.membership_tier DEFAULT 'Free',
    membership_expiry_date TIMESTAMP WITH TIME ZONE,
    is_verified BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    is_featured BOOLEAN DEFAULT FALSE,
    joined_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    description TEXT NOT NULL,
    working_hours JSONB NOT NULL,
    socials JSONB,
    seo JSONB,
    notification_settings JSONB,
    hero_slides JSONB, -- Storing as JSONB for simplicity as per types.ts implication, or could be separate table
    hero_image_url TEXT,
    
    -- Owner/Manager link (optional, if we link auth.users)
    owner_id UUID REFERENCES auth.users(id)
);

-- Table: services
CREATE TABLE public.services (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    duration_minutes INTEGER,
    position INTEGER DEFAULT 0
);

-- Table: deals
CREATE TABLE public.deals (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    discount_percentage DOUBLE PRECISION,
    original_price DOUBLE PRECISION,
    deal_price DOUBLE PRECISION,
    status public.deal_status DEFAULT 'Active'
);

-- Table: team_members
CREATE TABLE public.team_members (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    image_url TEXT
);

-- Table: media_items (Gallery)
CREATE TABLE public.media_items (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    type public.media_type DEFAULT 'IMAGE',
    category public.media_category DEFAULT 'Uncategorized',
    title TEXT,
    description TEXT,
    position INTEGER DEFAULT 0
);

-- Table: reviews
CREATE TABLE public.reviews (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id), -- Optional if anonymous reviews allowed, but better linked
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    user_name TEXT NOT NULL, -- Fallback if not linked or cached
    user_avatar_url TEXT, -- Fallback code
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    submitted_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status public.review_status DEFAULT 'Visible',
    reply JSONB -- { content: string, replied_date: string }
);

-- Table: staff_members (Internal business staff with access)
-- Note: types.ts had this as JSONB inside businesses, but relational is often better. 
-- For now, adhering to types.ts 'staff' field in 'businesses' might be simpler, 
-- but creating a table allows for future auth mapping. 
-- Let's stick to the SQL strict structure where possible, but if the app expects JSONB in select *, we can use a view or keep it JSONB.
-- DECISION: The `businesses` table above has `staff` removed from column definition to prefer a separate table approach (better practice),
-- BUT types.ts says "Kept as JSONB as it's tightly coupled 1-to-1". 
-- Wait, types.ts says: `staff: StaffMember[]; // Kept as JSONB`. 
-- To be safe and minimal change for frontend, let's ADD the staff column back to businesses as JSONB, 
-- OR create a view. Let's add it back to `businesses` table for now to match exactly what `types.ts` likely expects from a simple query.
ALTER TABLE public.businesses ADD COLUMN staff JSONB DEFAULT '[]'::JSONB;

-- Table: blog_posts (Platform blog)
CREATE TABLE public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    image_url TEXT NOT NULL,
    excerpt TEXT,
    author TEXT,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    category TEXT, -- simplified from relation
    content TEXT,
    view_count INTEGER DEFAULT 0
);

-- Table: business_blog_posts
CREATE TABLE public.business_blog_posts (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    slug TEXT NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT,
    image_url TEXT,
    content TEXT,
    author TEXT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    published_date TIMESTAMP WITH TIME ZONE,
    status public.business_blog_post_status DEFAULT 'Draft',
    view_count INTEGER DEFAULT 0,
    is_featured BOOLEAN DEFAULT FALSE,
    seo JSONB,
    UNIQUE(business_id, slug)
);

-- Table: profiles (Extends auth.users)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE,
    full_name TEXT,
    avatar_url TEXT,
    email TEXT,
    business_id BIGINT REFERENCES public.businesses(id),
    favorites BIGINT[] -- Array of business IDs
);

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, email)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Table: registration_requests
CREATE TABLE public.registration_requests (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    category public.business_category,
    address TEXT,
    tier public.membership_tier,
    status TEXT CHECK (status IN ('Pending', 'Approved', 'Rejected')),
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: orders
CREATE TABLE public.orders (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id),
    business_name TEXT,
    package_id TEXT, -- Assuming linked to a hardcoded package list or another table
    package_name TEXT,
    amount DOUBLE PRECISION,
    status public.order_status,
    payment_method TEXT,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    confirmed_at TIMESTAMP WITH TIME ZONE,
    notes TEXT
);

-- Table: appointments
CREATE TABLE public.appointments (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    service_id UUID REFERENCES public.services(id),
    service_name TEXT,
    staff_member_id TEXT, -- keeping flexible as per types
    customer_name TEXT NOT NULL,
    customer_email TEXT,
    customer_phone TEXT NOT NULL,
    date DATE NOT NULL,
    time_slot TIME NOT NULL,
    status public.appointment_status DEFAULT 'Pending',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: support_tickets
CREATE TABLE public.support_tickets (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    business_name TEXT,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    status public.ticket_status DEFAULT 'Open',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_reply_at TIMESTAMP WITH TIME ZONE,
    replies JSONB -- Array of TicketReply objects
);

-- Table: admin_users (Separate from auth.users or linked)
CREATE TABLE public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT, -- hashed
    role public.admin_user_role DEFAULT 'Editor',
    permissions JSONB,
    last_login TIMESTAMP WITH TIME ZONE,
    is_locked BOOLEAN DEFAULT FALSE
);

-- RLS Policies (Basic examples, should be refined)
ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public businesses are viewable by everyone" ON public.businesses FOR SELECT USING (true);
-- Add more specific policies as needed for owners vs public

ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public services are viewable by everyone" ON public.services FOR SELECT USING (true);

-- Storage Buckets (Execute this via Storage UI or API if SQL not supported for buckets in your environment, but standard pg_net/extensions might be needed. Usually easier in Dashboard)
-- INSERT INTO storage.buckets (id, name, public) VALUES ('business-images', 'business-images', true) ON CONFLICT DO NOTHING;

