-- ============================================
-- 1BEAUTY.ASIA - GROUND TRUTH SCHEMA
-- ============================================
-- Đây là file NGUỒN SỰ THẬT DUY NHẤT.
-- Chứa toàn bộ cấu trúc Database chuẩn, đã fix mọi lỗi.
-- ============================================
-- 1. ENUMS
CREATE TYPE public.membership_tier AS ENUM ('VIP', 'Premium', 'Free');
CREATE TYPE public.business_category AS ENUM (
    'Spa & Massage',
    'Hair Salon',
    'Nail Salon',
    'Beauty Clinic',
    'Dental Clinic'
);
CREATE TYPE public.admin_user_role AS ENUM ('Admin', 'Moderator', 'Editor');
CREATE TYPE public.order_status AS ENUM (
    'Pending',
    'Awaiting Confirmation',
    'Completed',
    'Rejected'
);
CREATE TYPE public.media_type AS ENUM ('IMAGE', 'VIDEO');
CREATE TYPE public.media_category AS ENUM (
    'Uncategorized',
    'Interior',
    'Exterior',
    'Staff',
    'Products'
);
CREATE TYPE public.business_blog_post_status AS ENUM ('Draft', 'Published');
CREATE TYPE public.review_status AS ENUM ('Visible', 'Hidden');
CREATE TYPE public.staff_member_role AS ENUM ('Admin', 'Editor');
CREATE TYPE public.appointment_status AS ENUM ('Pending', 'Confirmed', 'Cancelled', 'Completed');
CREATE TYPE public.deal_status AS ENUM ('Active', 'Expired', 'Scheduled');
CREATE TYPE public.ticket_status AS ENUM ('Open', 'In Progress', 'Closed');
-- 2. CORE TABLES
CREATE TABLE public.businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    logo_url TEXT,
    image_url TEXT NOT NULL,
    slogan TEXT,
    categories public.business_category [] NOT NULL,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    district TEXT NOT NULL,
    ward TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    tags TEXT [],
    phone TEXT NOT NULL,
    email TEXT,
    website TEXT,
    youtube_url TEXT,
    rating DOUBLE PRECISION DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    view_count INTEGER DEFAULT 0,
    membership_tier public.membership_tier DEFAULT 'Free',
    membership_expiry_date TIMESTAMP WITH TIME ZONE,
    is_verified BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    is_featured BOOLEAN DEFAULT FALSE,
    joined_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    description TEXT NOT NULL,
    working_hours JSONB NOT NULL,
    socials JSONB,
    seo JSONB,
    notification_settings JSONB,
    hero_slides JSONB,
    hero_image_url TEXT,
    staff JSONB DEFAULT '[]'::JSONB,
    owner_id UUID REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE,
    full_name TEXT,
    avatar_url TEXT,
    email TEXT,
    user_type TEXT DEFAULT 'user',
    business_id BIGINT REFERENCES public.businesses(id),
    favorites BIGINT []
);
CREATE TABLE public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT,
    role public.admin_user_role DEFAULT 'Editor',
    permissions JSONB,
    last_login TIMESTAMP WITH TIME ZONE,
    is_locked BOOLEAN DEFAULT FALSE
);
-- 3. UNIFIED AUTH RPC (THE BEST VERSION)
CREATE OR REPLACE FUNCTION public.get_user_context(p_user_id UUID) RETURNS JSONB SECURITY DEFINER
SET search_path = public AS $$
DECLARE v_profile RECORD;
v_business_id BIGINT;
v_role TEXT := 'user';
v_permissions JSONB := '[]'::jsonb;
BEGIN
SELECT * INTO v_profile
FROM public.profiles
WHERE id = p_user_id;
IF NOT FOUND THEN RETURN jsonb_build_object(
    'role',
    'user',
    'isDataLoaded',
    false,
    'error',
    'Profile not found'
);
END IF;
IF EXISTS (
    SELECT 1
    FROM public.admin_users
    WHERE email = v_profile.email
        AND is_locked = FALSE
) THEN v_role := 'admin';
v_permissions := '["all"]'::jsonb;
ELSE
SELECT id INTO v_business_id
FROM public.businesses
WHERE owner_id = p_user_id
LIMIT 1;
IF v_business_id IS NOT NULL THEN v_role := 'business_owner';
ELSE
SELECT business_id INTO v_business_id
FROM public.business_staff
WHERE user_id = p_user_id
LIMIT 1;
IF v_business_id IS NOT NULL THEN v_role := 'business_staff';
END IF;
END IF;
END IF;
IF v_role = 'business_owner'
AND (
    v_profile.user_type != 'business'
    OR v_profile.business_id IS NULL
) THEN
UPDATE public.profiles
SET user_type = 'business',
    business_id = v_business_id
WHERE id = p_user_id;
END IF;
RETURN jsonb_build_object(
    'profile',
    to_jsonb(v_profile),
    'role',
    v_role,
    'businessId',
    v_business_id,
    'permissions',
    v_permissions,
    'isDataLoaded',
    TRUE
);
END;
$$ LANGUAGE plpgsql;
-- 4. STRICT NEW USER TRIGGER
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS TRIGGER SECURITY DEFINER
SET search_path = public AS $$
DECLARE v_user_type TEXT;
v_business_id BIGINT;
v_slug TEXT;
BEGIN v_user_type := COALESCE(new.raw_user_meta_data->>'user_type', 'user');
INSERT INTO public.profiles (id, full_name, avatar_url, email, user_type)
VALUES (
        new.id,
        COALESCE(
            new.raw_user_meta_data->>'full_name',
            new.raw_user_meta_data->>'business_name',
            'User'
        ),
        new.raw_user_meta_data->>'avatar_url',
        new.email,
        v_user_type
    ) ON CONFLICT (id) DO
UPDATE
SET full_name = EXCLUDED.full_name,
    email = EXCLUDED.email,
    user_type = EXCLUDED.user_type;
IF v_user_type = 'business'
AND new.raw_user_meta_data->>'business_name' IS NOT NULL THEN
SELECT id INTO v_business_id
FROM public.businesses
WHERE owner_id = new.id
LIMIT 1;
IF v_business_id IS NULL THEN v_slug := lower(
    regexp_replace(
        new.raw_user_meta_data->>'business_name',
        '[^a-zA-Z0-9]+',
        '-',
        'g'
    )
) || '-' || floor(random() * 1000)::text;
INSERT INTO public.businesses (
        name,
        slug,
        owner_id,
        is_active,
        is_verified,
        address,
        city,
        district,
        ward,
        phone,
        description,
        working_hours,
        image_url,
        categories
    )
VALUES (
        new.raw_user_meta_data->>'business_name',
        v_slug,
        new.id,
        true,
        false,
        COALESCE(new.raw_user_meta_data->>'address', 'N/A'),
        'TP. Hồ Chí Minh',
        'Quận 1',
        'Phường Bến Thành',
        COALESCE(new.raw_user_meta_data->>'phone', 'N/A'),
        COALESCE(new.raw_user_meta_data->>'description', ''),
        '{"monday": {"open": "09:00", "close": "18:00"}}'::jsonb,
        'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&auto=format&fit=crop&q=60',
        ARRAY ['Spa & Massage'::public.business_category]
    )
RETURNING id INTO v_business_id;
END IF;
UPDATE public.profiles
SET business_id = v_business_id
WHERE id = new.id;
END IF;
RETURN new;
END;
$$ LANGUAGE plpgsql;