-- ============================================
-- 1BEAUTY.ASIA - DATABASE SCHEMA v1.0
-- ============================================
-- Consolidated Schema - Single Source of Truth
-- Created: 2025-01-05
-- Version: 1.0
-- 
-- This schema consolidates all SQL definitions from:
-- - supabase_new_schema.sql (base schema)
-- - fix_full_database.sql (additional tables)
-- - add_foreign_key_indexes.sql (indexes)
-- - migrations (fixes and updates)
-- ============================================
-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- ============================================
-- ENUMS
-- ============================================
-- Drop existing types to ensure clean enum definitions (for fresh installs)
DROP TYPE IF EXISTS public.ticket_status CASCADE;
DROP TYPE IF EXISTS public.deal_status CASCADE;
DROP TYPE IF EXISTS public.appointment_status CASCADE;
DROP TYPE IF EXISTS public.staff_member_role CASCADE;
DROP TYPE IF EXISTS public.review_status CASCADE;
DROP TYPE IF EXISTS public.business_blog_post_status CASCADE;
DROP TYPE IF EXISTS public.media_category CASCADE;
DROP TYPE IF EXISTS public.media_type CASCADE;
DROP TYPE IF EXISTS public.order_status CASCADE;
DROP TYPE IF EXISTS public.admin_user_role CASCADE;
DROP TYPE IF EXISTS public.business_category CASCADE;
DROP TYPE IF EXISTS public.membership_tier CASCADE;
-- Create Enums (matched with types.ts)
CREATE TYPE public.membership_tier AS ENUM ('VIP', 'Premium', 'Free');
CREATE TYPE public.business_category AS ENUM (
    'Spa & Massage',
    'Hair Salon',
    'Nail Salon',
    'Beauty Clinic',
    'Dental Clinic'
);
CREATE TYPE public.admin_user_role AS ENUM ('Admin', 'Moderator', 'Editor');
CREATE TYPE public.order_status AS ENUM (
    'Pending',
    'Awaiting Confirmation',
    'Completed',
    'Rejected'
);
CREATE TYPE public.media_type AS ENUM ('IMAGE', 'VIDEO');
CREATE TYPE public.media_category AS ENUM (
    'Uncategorized',
    'Interior',
    'Exterior',
    'Staff',
    'Products'
);
CREATE TYPE public.business_blog_post_status AS ENUM ('Draft', 'Published');
CREATE TYPE public.review_status AS ENUM ('Visible', 'Hidden');
CREATE TYPE public.staff_member_role AS ENUM ('Admin', 'Editor');
CREATE TYPE public.appointment_status AS ENUM ('Pending', 'Confirmed', 'Cancelled', 'Completed');
CREATE TYPE public.deal_status AS ENUM ('Active', 'Expired', 'Scheduled');
CREATE TYPE public.ticket_status AS ENUM ('Open', 'In Progress', 'Closed');
-- ============================================
-- BUSINESS TABLES
-- ============================================
-- Table: businesses (Core table)
CREATE TABLE public.businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    logo_url TEXT,
    image_url TEXT NOT NULL,
    slogan TEXT,
    categories public.business_category [] NOT NULL,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    district TEXT NOT NULL,
    ward TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    tags TEXT [],
    phone TEXT NOT NULL,
    email TEXT,
    website TEXT,
    youtube_url TEXT,
    rating DOUBLE PRECISION DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    view_count INTEGER DEFAULT 0,
    membership_tier public.membership_tier DEFAULT 'Free',
    membership_expiry_date TIMESTAMP WITH TIME ZONE,
    is_verified BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    is_featured BOOLEAN DEFAULT FALSE,
    joined_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    description TEXT NOT NULL,
    working_hours JSONB NOT NULL,
    socials JSONB,
    seo JSONB,
    notification_settings JSONB,
    hero_slides JSONB,
    hero_image_url TEXT,
    staff JSONB DEFAULT '[]'::JSONB,
    owner_id UUID REFERENCES auth.users(id)
);
-- Table: services
CREATE TABLE public.services (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    duration_minutes INTEGER,
    position INTEGER DEFAULT 0
);
-- Table: deals
CREATE TABLE public.deals (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    discount_percentage DOUBLE PRECISION,
    original_price DOUBLE PRECISION,
    deal_price DOUBLE PRECISION,
    status public.deal_status DEFAULT 'Active'
);
-- Table: team_members
CREATE TABLE public.team_members (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    image_url TEXT
);
-- Table: media_items (Gallery)
CREATE TABLE public.media_items (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    type public.media_type DEFAULT 'IMAGE',
    category public.media_category DEFAULT 'Uncategorized',
    title TEXT,
    description TEXT,
    position INTEGER DEFAULT 0
);
-- Table: reviews
CREATE TABLE public.reviews (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    user_name TEXT NOT NULL,
    user_avatar_url TEXT,
    rating INTEGER CHECK (
        rating >= 1
        AND rating <= 5
    ),
    comment TEXT,
    submitted_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status public.review_status DEFAULT 'Visible',
    reply JSONB
);
-- ============================================
-- BLOG TABLES
-- ============================================
-- Table: blog_posts (Platform blog)
CREATE TABLE public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    image_url TEXT NOT NULL,
    excerpt TEXT,
    author TEXT,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    category TEXT,
    content TEXT,
    view_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'Published' CHECK (status IN ('Draft', 'Published')),
    seo JSONB DEFAULT '{"title": "", "description": "", "keywords": ""}'::JSONB,
    is_featured BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Table: blog_categories
CREATE TABLE public.blog_categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Table: blog_comments
CREATE TABLE public.blog_comments (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES public.blog_posts(id) ON DELETE CASCADE,
    author_name TEXT NOT NULL,
    content TEXT NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Table: business_blog_posts
CREATE TABLE public.business_blog_posts (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    slug TEXT NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT,
    image_url TEXT,
    content TEXT,
    author TEXT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    published_date TIMESTAMP WITH TIME ZONE,
    status public.business_blog_post_status DEFAULT 'Draft',
    view_count INTEGER DEFAULT 0,
    is_featured BOOLEAN DEFAULT FALSE,
    seo JSONB,
    UNIQUE(business_id, slug)
);
-- ============================================
-- USER & AUTH TABLES
-- ============================================
-- Table: profiles (Extends auth.users)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE,
    full_name TEXT,
    avatar_url TEXT,
    email TEXT,
    business_id BIGINT REFERENCES public.businesses(id),
    favorites BIGINT []
);
-- Table: admin_users
CREATE TABLE public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT,
    role public.admin_user_role DEFAULT 'Editor',
    permissions JSONB,
    last_login TIMESTAMP WITH TIME ZONE,
    is_locked BOOLEAN DEFAULT FALSE
);
-- Table: business_staff
CREATE TABLE public.business_staff (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    business_id BIGINT NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role public.staff_member_role NOT NULL DEFAULT 'Editor',
    permissions JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(business_id, user_id)
);
-- ============================================
-- BUSINESS OPERATIONS TABLES
-- ============================================
-- Table: registration_requests
CREATE TABLE public.registration_requests (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    category public.business_category,
    address TEXT,
    tier public.membership_tier,
    status TEXT CHECK (status IN ('Pending', 'Approved', 'Rejected')),
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Table: orders
CREATE TABLE public.orders (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id),
    business_name TEXT,
    package_id TEXT,
    package_name TEXT,
    amount DOUBLE PRECISION,
    status public.order_status,
    payment_method TEXT,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    confirmed_at TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    payment_proof_url TEXT
);
-- Table: membership_packages
CREATE TABLE public.membership_packages (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    duration_months INTEGER NOT NULL,
    description TEXT,
    features TEXT [],
    permissions JSONB,
    is_popular BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE
);
-- Table: appointments
CREATE TABLE public.appointments (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    service_id UUID REFERENCES public.services(id),
    service_name TEXT,
    staff_member_id TEXT,
    customer_name TEXT NOT NULL,
    customer_email TEXT,
    customer_phone TEXT NOT NULL,
    date DATE NOT NULL,
    time_slot TIME NOT NULL,
    status public.appointment_status DEFAULT 'Pending',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Table: support_tickets
CREATE TABLE public.support_tickets (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    business_name TEXT,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    status public.ticket_status DEFAULT 'Open',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_reply_at TIMESTAMP WITH TIME ZONE,
    replies JSONB
);
-- ============================================
-- ANALYTICS TABLES
-- ============================================
-- Table: page_views
CREATE TABLE public.page_views (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    page_type TEXT NOT NULL,
    page_id TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE
    SET NULL,
        session_id TEXT,
        ip_address TEXT,
        user_agent TEXT,
        referrer TEXT,
        viewed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Table: conversions
CREATE TABLE public.conversions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    conversion_type TEXT NOT NULL,
    source TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE
    SET NULL,
        session_id TEXT,
        metadata JSONB,
        converted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- ============================================
-- SYSTEM TABLES
-- ============================================
-- Table: announcements
CREATE TABLE public.announcements (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT CHECK (type IN ('info', 'warning', 'success')) DEFAULT 'info',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Table: app_settings
CREATE TABLE public.app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settings_data JSONB
);
-- Table: page_content
CREATE TABLE public.page_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_name TEXT NOT NULL UNIQUE,
    content_data JSONB
);
-- Table: admin_activity_logs
CREATE TABLE public.admin_activity_logs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    admin_username TEXT NOT NULL,
    action TEXT NOT NULL,
    details TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Table: email_notifications_log
CREATE TABLE public.email_notifications_log (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    recipient_email TEXT NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Table: abuse_reports
CREATE TABLE public.abuse_reports (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    review_id UUID NOT NULL REFERENCES public.reviews(id) ON DELETE CASCADE,
    reporter_id UUID REFERENCES auth.users(id) ON DELETE
    SET NULL,
        reason TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'Pending' CHECK (
            status IN ('Pending', 'Reviewed', 'Resolved', 'Dismissed')
        ),
        admin_notes TEXT,
        reviewed_by UUID REFERENCES auth.users(id) ON DELETE
    SET NULL,
        reviewed_at TIMESTAMP WITH TIME ZONE,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- ============================================
-- INDEXES
-- ============================================
-- Indexes for foreign key columns (for query performance)
CREATE INDEX IF NOT EXISTS idx_services_business_id ON public.services(business_id);
CREATE INDEX IF NOT EXISTS idx_deals_business_id ON public.deals(business_id);
CREATE INDEX IF NOT EXISTS idx_team_members_business_id ON public.team_members(business_id);
CREATE INDEX IF NOT EXISTS idx_media_items_business_id ON public.media_items(business_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON public.reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_business_id ON public.reviews(business_id);
CREATE INDEX IF NOT EXISTS idx_business_blog_posts_business_id ON public.business_blog_posts(business_id);
CREATE INDEX IF NOT EXISTS idx_profiles_business_id ON public.profiles(business_id);
CREATE INDEX IF NOT EXISTS idx_appointments_business_id ON public.appointments(business_id);
CREATE INDEX IF NOT EXISTS idx_appointments_service_id ON public.appointments(service_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_business_id ON public.support_tickets(business_id);
CREATE INDEX IF NOT EXISTS idx_orders_business_id ON public.orders(business_id);
-- Analytics Indexes
CREATE INDEX IF NOT EXISTS idx_page_views_page_type ON public.page_views(page_type);
CREATE INDEX IF NOT EXISTS idx_page_views_page_id ON public.page_views(page_id);
CREATE INDEX IF NOT EXISTS idx_page_views_viewed_at ON public.page_views(viewed_at);
CREATE INDEX IF NOT EXISTS idx_conversions_business_id ON public.conversions(business_id);
CREATE INDEX IF NOT EXISTS idx_conversions_type ON public.conversions(conversion_type);
CREATE INDEX IF NOT EXISTS idx_conversions_converted_at ON public.conversions(converted_at);
-- Admin/System Indexes
CREATE INDEX IF NOT EXISTS idx_admin_activity_logs_admin_username ON public.admin_activity_logs(admin_username);
CREATE INDEX IF NOT EXISTS idx_admin_activity_logs_timestamp ON public.admin_activity_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_email_notifications_log_recipient ON public.email_notifications_log(recipient_email);
CREATE INDEX IF NOT EXISTS idx_abuse_reports_review_id ON public.abuse_reports(review_id);
CREATE INDEX IF NOT EXISTS idx_abuse_reports_status ON public.abuse_reports(status);
-- Additional Performance Indexes
CREATE INDEX IF NOT EXISTS idx_page_content_page_name ON public.page_content(page_name)
WHERE page_name IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_blog_categories_name ON public.blog_categories(name);
CREATE INDEX IF NOT EXISTS idx_membership_packages_active_price ON public.membership_packages(is_active, price)
WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_membership_packages_is_active ON public.membership_packages(is_active)
WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_blog_posts_status ON public.blog_posts(status);
CREATE INDEX IF NOT EXISTS idx_blog_posts_date_desc ON public.blog_posts(date DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_blog_comments_post_id_date ON public.blog_comments(post_id, date);
CREATE INDEX IF NOT EXISTS idx_blog_comments_date ON public.blog_comments(date DESC);
CREATE INDEX IF NOT EXISTS idx_business_staff_business_id ON public.business_staff(business_id);
CREATE INDEX IF NOT EXISTS idx_business_staff_user_id ON public.business_staff(user_id);
-- Indexes for commonly queried columns
CREATE INDEX IF NOT EXISTS idx_businesses_slug ON public.businesses(slug);
CREATE INDEX IF NOT EXISTS idx_businesses_is_active ON public.businesses(is_active);
CREATE INDEX IF NOT EXISTS idx_businesses_membership_tier ON public.businesses(membership_tier);
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON public.blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_registration_requests_status ON public.registration_requests(status);
-- ============================================
-- FUNCTIONS & TRIGGERS
-- ============================================
-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS TRIGGER AS $$ BEGIN
INSERT INTO public.profiles (id, full_name, avatar_url, email)
VALUES (
        new.id,
        new.raw_user_meta_data->>'full_name',
        new.raw_user_meta_data->>'avatar_url',
        new.email
    );
RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- Trigger for new user
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER
INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================
-- Note: Basic RLS enabled. Detailed policies will be defined in A3 - RLS & Security Audit
-- Enable RLS on all tables
ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registration_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_content ENABLE ROW LEVEL SECURITY;
-- ============================================
-- END OF SCHEMA v1.0
-- ============================================