-- ============================================
-- MIGRATION: Align Existing Database to Schema v1.0
-- ============================================
-- Purpose: Safely migrate existing database structure to match schema_v1.0.sql
-- Created: 2025-01-05
-- Version: 1.0
-- 
-- This migration script:
-- - Creates missing tables (CREATE TABLE IF NOT EXISTS)
-- - Creates missing enums
-- - Creates missing indexes
-- - Enables RLS on tables that don't have it
-- - Does NOT drop existing tables or data
-- ============================================

-- Enable UUID extension (if not exists)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- ENUMS (Create if not exists)
-- ============================================

DO $$ BEGIN
    CREATE TYPE public.membership_tier AS ENUM ('VIP', 'Premium', 'Free');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.business_category AS ENUM ('Spa & Massage', 'Hair Salon', 'Nail Salon', 'Beauty Clinic', 'Dental Clinic');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.admin_user_role AS ENUM ('Admin', 'Moderator', 'Editor');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.order_status AS ENUM ('Pending', 'Awaiting Confirmation', 'Completed', 'Rejected');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.media_type AS ENUM ('IMAGE', 'VIDEO');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.media_category AS ENUM ('Uncategorized', 'Interior', 'Exterior', 'Staff', 'Products');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.business_blog_post_status AS ENUM ('Draft', 'Published');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.review_status AS ENUM ('Visible', 'Hidden');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.staff_member_role AS ENUM ('Admin', 'Editor');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.appointment_status AS ENUM ('Pending', 'Confirmed', 'Cancelled', 'Completed');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.deal_status AS ENUM ('Active', 'Expired', 'Scheduled');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.ticket_status AS ENUM ('Open', 'In Progress', 'Closed');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- ============================================
-- CREATE MISSING TABLES (IF NOT EXISTS)
-- ============================================
-- Note: Using CREATE TABLE IF NOT EXISTS to avoid errors on existing tables
-- This migration assumes tables may already exist

-- Table: businesses (Core table)
CREATE TABLE IF NOT EXISTS public.businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    logo_url TEXT,
    image_url TEXT NOT NULL,
    slogan TEXT,
    categories public.business_category[] NOT NULL,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    district TEXT NOT NULL,
    ward TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    tags TEXT[],
    phone TEXT NOT NULL,
    email TEXT,
    website TEXT,
    youtube_url TEXT,
    rating DOUBLE PRECISION DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    view_count INTEGER DEFAULT 0,
    membership_tier public.membership_tier DEFAULT 'Free',
    membership_expiry_date TIMESTAMP WITH TIME ZONE,
    is_verified BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    is_featured BOOLEAN DEFAULT FALSE,
    joined_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    description TEXT NOT NULL,
    working_hours JSONB NOT NULL,
    socials JSONB,
    seo JSONB,
    notification_settings JSONB,
    hero_slides JSONB,
    hero_image_url TEXT,
    staff JSONB DEFAULT '[]'::JSONB,
    owner_id UUID REFERENCES auth.users(id)
);

-- Table: services
CREATE TABLE IF NOT EXISTS public.services (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    duration_minutes INTEGER,
    position INTEGER DEFAULT 0
);

-- Table: deals
CREATE TABLE IF NOT EXISTS public.deals (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    discount_percentage DOUBLE PRECISION,
    original_price DOUBLE PRECISION,
    deal_price DOUBLE PRECISION,
    status public.deal_status DEFAULT 'Active'
);

-- Table: team_members
CREATE TABLE IF NOT EXISTS public.team_members (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    image_url TEXT
);

-- Table: media_items (Gallery)
CREATE TABLE IF NOT EXISTS public.media_items (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    type public.media_type DEFAULT 'IMAGE',
    category public.media_category DEFAULT 'Uncategorized',
    title TEXT,
    description TEXT,
    position INTEGER DEFAULT 0
);

-- Table: reviews
CREATE TABLE IF NOT EXISTS public.reviews (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    user_name TEXT NOT NULL,
    user_avatar_url TEXT,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    submitted_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status public.review_status DEFAULT 'Visible',
    reply JSONB
);

-- Table: blog_posts (Platform blog)
CREATE TABLE IF NOT EXISTS public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    image_url TEXT NOT NULL,
    excerpt TEXT,
    author TEXT,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    category TEXT,
    content TEXT,
    view_count INTEGER DEFAULT 0
);

-- Table: business_blog_posts
CREATE TABLE IF NOT EXISTS public.business_blog_posts (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    slug TEXT NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT,
    image_url TEXT,
    content TEXT,
    author TEXT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    published_date TIMESTAMP WITH TIME ZONE,
    status public.business_blog_post_status DEFAULT 'Draft',
    view_count INTEGER DEFAULT 0,
    is_featured BOOLEAN DEFAULT FALSE,
    seo JSONB,
    UNIQUE(business_id, slug)
);

-- Table: profiles (Extends auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE,
    full_name TEXT,
    avatar_url TEXT,
    email TEXT,
    business_id BIGINT REFERENCES public.businesses(id),
    favorites BIGINT[]
);

-- Table: admin_users
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT,
    role public.admin_user_role DEFAULT 'Editor',
    permissions JSONB,
    last_login TIMESTAMP WITH TIME ZONE,
    is_locked BOOLEAN DEFAULT FALSE
);

-- Table: registration_requests
CREATE TABLE IF NOT EXISTS public.registration_requests (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    category public.business_category,
    address TEXT,
    tier public.membership_tier,
    status TEXT CHECK (status IN ('Pending', 'Approved', 'Rejected')),
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: orders
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id),
    business_name TEXT,
    package_id TEXT,
    package_name TEXT,
    amount DOUBLE PRECISION,
    status public.order_status,
    payment_method TEXT,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    confirmed_at TIMESTAMP WITH TIME ZONE,
    notes TEXT
);

-- Table: appointments
CREATE TABLE IF NOT EXISTS public.appointments (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    service_id UUID REFERENCES public.services(id),
    service_name TEXT,
    staff_member_id TEXT,
    customer_name TEXT NOT NULL,
    customer_email TEXT,
    customer_phone TEXT NOT NULL,
    date DATE NOT NULL,
    time_slot TIME NOT NULL,
    status public.appointment_status DEFAULT 'Pending',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: support_tickets
CREATE TABLE IF NOT EXISTS public.support_tickets (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    business_name TEXT,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    status public.ticket_status DEFAULT 'Open',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_reply_at TIMESTAMP WITH TIME ZONE,
    replies JSONB
);

-- Table: announcements
CREATE TABLE IF NOT EXISTS public.announcements (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT CHECK (type IN ('info', 'warning', 'success')) DEFAULT 'info',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: app_settings
CREATE TABLE IF NOT EXISTS public.app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settings_data JSONB
);

-- Table: page_content
CREATE TABLE IF NOT EXISTS public.page_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_name TEXT NOT NULL UNIQUE,
    content_data JSONB
);

-- ============================================
-- CREATE MISSING INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS idx_services_business_id ON public.services(business_id);
CREATE INDEX IF NOT EXISTS idx_deals_business_id ON public.deals(business_id);
CREATE INDEX IF NOT EXISTS idx_team_members_business_id ON public.team_members(business_id);
CREATE INDEX IF NOT EXISTS idx_media_items_business_id ON public.media_items(business_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON public.reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_business_id ON public.reviews(business_id);
CREATE INDEX IF NOT EXISTS idx_business_blog_posts_business_id ON public.business_blog_posts(business_id);
CREATE INDEX IF NOT EXISTS idx_profiles_business_id ON public.profiles(business_id);
CREATE INDEX IF NOT EXISTS idx_appointments_business_id ON public.appointments(business_id);
CREATE INDEX IF NOT EXISTS idx_appointments_service_id ON public.appointments(service_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_business_id ON public.support_tickets(business_id);
CREATE INDEX IF NOT EXISTS idx_orders_business_id ON public.orders(business_id);
CREATE INDEX IF NOT EXISTS idx_businesses_slug ON public.businesses(slug);
CREATE INDEX IF NOT EXISTS idx_businesses_is_active ON public.businesses(is_active);
CREATE INDEX IF NOT EXISTS idx_businesses_membership_tier ON public.businesses(membership_tier);
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON public.blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_registration_requests_status ON public.registration_requests(status);

-- ============================================
-- CREATE FUNCTION & TRIGGER (IF NOT EXISTS)
-- ============================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, email)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', new.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================
-- ENABLE RLS ON ALL TABLES (IF NOT ENABLED)
-- ============================================
-- Note: This only enables RLS, does not create policies
-- Detailed policies will be created in A3 - RLS & Security Audit

ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registration_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_content ENABLE ROW LEVEL SECURITY;

-- ============================================
-- END OF MIGRATION
-- ============================================
-- This migration aligns existing database structure to schema_v1.0
-- It does NOT drop existing tables or data
-- It creates missing structures safely using IF NOT EXISTS patterns


