#!/usr/bin/env node

/**
 * Sync Environment Variables from Vercel to Local
 * 
 * Usage:
 * 1. Export env vars from Vercel Dashboard to .env.vercel
 * 2. Run: node scripts/sync-env.js
 */

const fs = require('fs');
const path = require('path');

// Required environment variables
const REQUIRED_VARS = [
  'VITE_SUPABASE_URL',
  'VITE_SUPABASE_ANON_KEY'
];

// Optional environment variables
const OPTIONAL_VARS = [
  'GEMINI_API_KEY'
];

// Legacy variables (should be removed)
const LEGACY_VARS = [
  'SUPABASE_URL',
  'SUPABASE_ANON_KEY',
  'API_KEY'
];

// File paths
const ENV_VERCEL_PATH = path.join(__dirname, '..', '.env.vercel');
const ENV_LOCAL_PATH = path.join(__dirname, '..', '.env.local');
const ENV_EXAMPLE_PATH = path.join(__dirname, '..', 'docs', 'env.example');

function readEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const content = fs.readFileSync(filePath, 'utf-8');
  const vars = {};

  content.split('\n').forEach(line => {
    line = line.trim();
    if (!line || line.startsWith('#')) {
      return;
    }

    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      let value = match[2].trim();
      
      // Remove quotes if present
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }

      vars[key] = value;
    }
  });

  return vars;
}

function writeEnvFile(filePath, vars, comments = {}) {
  const lines = [];
  
  // Add header
  lines.push('# Environment Variables');
  lines.push('# Generated by sync-env.js');
  lines.push(`# Date: ${new Date().toISOString()}`);
  lines.push('');

  // Add variables
  Object.entries(vars).forEach(([key, value]) => {
    if (comments[key]) {
      lines.push(`# ${comments[key]}`);
    }
    lines.push(`${key}="${value}"`);
    lines.push('');
  });

  fs.writeFileSync(filePath, lines.join('\n'), 'utf-8');
}

function validateValue(key, value) {
  if (!value || value.trim() === '') {
    return { valid: false, error: 'Empty value' };
  }

  // Check for placeholders
  const placeholders = [
    'your-project-url',
    'your-public-anon-key',
    'your-gemini-api-key',
    'your-supabase-url',
    'your-anon-key'
  ];

  for (const placeholder of placeholders) {
    if (value.toLowerCase().includes(placeholder)) {
      return { valid: false, error: `Contains placeholder: ${placeholder}` };
    }
  }

  // Validate format
  if (key === 'VITE_SUPABASE_URL' && !value.startsWith('https://')) {
    return { valid: false, error: 'Must start with https://' };
  }

  if (key === 'VITE_SUPABASE_ANON_KEY' && !value.startsWith('eyJ')) {
    return { valid: false, error: 'Invalid format (should start with eyJ)' };
  }

  if (key === 'GEMINI_API_KEY' && !value.startsWith('AIza')) {
    return { valid: false, error: 'Invalid format (should start with AIza)' };
  }

  return { valid: true };
}

function main() {
  console.log('🔄 Syncing Environment Variables from Vercel...\n');

  // Read Vercel env file
  if (!fs.existsSync(ENV_VERCEL_PATH)) {
    console.error('❌ Error: .env.vercel file not found!');
    console.log('\n📝 Please:');
    console.log('1. Export environment variables from Vercel Dashboard');
    console.log('2. Save to .env.vercel file in project root');
    console.log('3. Format: VARIABLE_NAME=value (one per line)');
    console.log('\nSee: scripts/sync-env-from-vercel.md for instructions');
    process.exit(1);
  }

  const vercelVars = readEnvFile(ENV_VERCEL_PATH);
  console.log(`✅ Read ${Object.keys(vercelVars).length} variables from .env.vercel\n`);

  // Check for required variables
  const missing = [];
  const invalid = [];
  const legacy = [];
  const found = {};

  REQUIRED_VARS.forEach(key => {
    if (!vercelVars[key]) {
      missing.push(key);
    } else {
      const validation = validateValue(key, vercelVars[key]);
      if (!validation.valid) {
        invalid.push({ key, error: validation.error });
      } else {
        found[key] = vercelVars[key];
      }
    }
  });

  // Check optional variables
  OPTIONAL_VARS.forEach(key => {
    if (vercelVars[key]) {
      const validation = validateValue(key, vercelVars[key]);
      if (!validation.valid) {
        invalid.push({ key, error: validation.error });
      } else {
        found[key] = vercelVars[key];
      }
    }
  });

  // Check for legacy variables
  LEGACY_VARS.forEach(key => {
    if (vercelVars[key]) {
      legacy.push(key);
    }
  });

  // Report results
  console.log('📊 Analysis Results:\n');

  if (missing.length > 0) {
    console.log('❌ Missing Required Variables:');
    missing.forEach(key => console.log(`   - ${key}`));
    console.log('');
  }

  if (invalid.length > 0) {
    console.log('⚠️  Invalid Variables:');
    invalid.forEach(({ key, error }) => {
      console.log(`   - ${key}: ${error}`);
    });
    console.log('');
  }

  if (legacy.length > 0) {
    console.log('⚠️  Legacy Variables (should be removed):');
    legacy.forEach(key => console.log(`   - ${key}`));
    console.log('');
  }

  if (Object.keys(found).length > 0) {
    console.log('✅ Valid Variables Found:');
    Object.keys(found).forEach(key => {
      const value = found[key];
      const displayValue = value.length > 50 
        ? `${value.substring(0, 47)}...` 
        : value;
      console.log(`   - ${key} = ${displayValue}`);
    });
    console.log('');
  }

  // Check for unknown variables
  const knownVars = [...REQUIRED_VARS, ...OPTIONAL_VARS, ...LEGACY_VARS];
  const unknownVars = Object.keys(vercelVars).filter(
    key => !knownVars.includes(key)
  );

  if (unknownVars.length > 0) {
    console.log('❓ Unknown Variables (not in requirements):');
    unknownVars.forEach(key => console.log(`   - ${key}`));
    console.log('');
  }

  // Create .env.local if valid
  if (missing.length === 0 && invalid.length === 0) {
    const comments = {
      'VITE_SUPABASE_URL': 'Supabase project URL (REQUIRED)',
      'VITE_SUPABASE_ANON_KEY': 'Supabase anonymous/public key (REQUIRED)',
      'GEMINI_API_KEY': 'Google Gemini API key (OPTIONAL - for AI features)'
    };

    writeEnvFile(ENV_LOCAL_PATH, found, comments);
    console.log(`✅ Created .env.local with ${Object.keys(found).length} variables\n`);

    // Verify completeness
    console.log('✅ Verification:');
    console.log('   - All required variables present');
    console.log('   - All values validated');
    console.log('   - .env.local created successfully');
    console.log('   - Ready for local development\n');

    if (legacy.length > 0) {
      console.log('⚠️  Recommendation: Remove legacy variables from Vercel:');
      legacy.forEach(key => console.log(`   - ${key}`));
      console.log('');
    }

    if (unknownVars.length > 0) {
      console.log('⚠️  Note: Unknown variables found (may be from other projects)');
      console.log('');
    }

    console.log('🎉 Sync complete! You can now run: npm run dev');
  } else {
    console.log('❌ Sync failed. Please fix the issues above and try again.');
    process.exit(1);
  }
}

main();
