-- Restore Missing Tables (Announcements, App Settings, Page Content)
-- 1. Announcements
CREATE TABLE IF NOT EXISTS public.announcements (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT CHECK (type IN ('info', 'warning', 'success')) DEFAULT 'info',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- 2. App Settings
CREATE TABLE IF NOT EXISTS public.app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settings_data JSONB
);
-- Insert default settings if not exists
INSERT INTO public.app_settings (id, settings_data)
VALUES (
        1,
        '{
        "siteName": "Beauty Directory",
        "supportEmail": "support@beautydir.com",
        "maintenanceMode": false,
        "bankDetails": {
            "bankName": "MB Bank",
            "accountName": "BEAUTY DIR CO",
            "accountNumber": "0000000000",
            "transferNote": "Payment for order [code]"
        }
    }'::JSONB
    ) ON CONFLICT (id) DO NOTHING;
-- 3. Page Content
CREATE TABLE IF NOT EXISTS public.page_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_name TEXT NOT NULL UNIQUE,
    content_data JSONB
);
-- 4. Enable RLS (Optional but good)
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public announcements are viewable by everyone" ON public.announcements FOR
SELECT USING (true);
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Settings viewable by everyone" ON public.app_settings FOR
SELECT USING (true);
ALTER TABLE public.page_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Page content viewable by everyone" ON public.page_content FOR
SELECT USING (true);